# Generated by Django 4.0.10 on 2023-11-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('numU', models.IntegerField(default=0, null=True)),
                ('numD', models.IntegerField(default=0, null=True)),
                ('resul', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
